#!/bin/bash
#SBATCH -A m3793
#SBATCH -N 16
#SBATCH -C knl
#SBATCH -q debug
#SBATCH -J l2g_lammps
#SBATCH -t 00:05:00


HOME="$(pwd)"
OUTPUT_DIR="$HOME/output"
mkdir -p "$OUTPUT_DIR"


module load lammps


export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread


srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.0> $OUTPUT_DIR/out.0 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.1> $OUTPUT_DIR/out.1 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.2> $OUTPUT_DIR/out.2 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.3> $OUTPUT_DIR/out.3 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.4> $OUTPUT_DIR/out.4 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.5> $OUTPUT_DIR/out.5 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.6> $OUTPUT_DIR/out.6 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.7> $OUTPUT_DIR/out.7 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.8> $OUTPUT_DIR/out.8 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.9> $OUTPUT_DIR/out.9 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.10> $OUTPUT_DIR/out.10 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.11> $OUTPUT_DIR/out.11 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.12> $OUTPUT_DIR/out.12 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.13> $OUTPUT_DIR/out.13 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.14> $OUTPUT_DIR/out.14 &

srun -N 1 -n 64 -c 1 --cpu-bind=cores lmp_cori  -in $HOME/input/in.15> $OUTPUT_DIR/out.15 &

wait
touch flag